### ISSUE TITLE
Slowness in panels with lots of resources

### ISSUE THREAD

**Issue by nicollassilva** [pxlrbt/filament-spotlight#5] opened 2022-04-08 04:06 UTC
I noticed that when I added Spotlight to my dashboard, the pages became 2~3 seconds slower to load. I have approximately 30 resources.

**Comment by pxlrbt** [comment] 2023-04-04 05:42
I don't think this was solved. Any reason you closed that issue?

**Comment by nicollassilva** [comment] 2023-05-19 12:16
@pxlrbt I waited for some solution for some weeks, then I decided to remove it from my project because it was really slow to register all the resources. Maybe a cache would help, I don't know if it already exists. But anyway, I don't think it's solved yet.

**Comment by pxlrbt** [comment] 2023-05-24 19:58
Closing this for now as I cannot reproduce it. Tested with an app that has 20 resources and it added an extra `0.001ms` to the page load. If anyone has a reproduction repo I am happy to have a look

**Closed by pxlrbt** 2023-05-24 19:58 UTC
